server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_data?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bigdata.bigdataserver.pojo